apiVersion: apps/v1
kind: Deployment
metadata:
  name: internet-banking-fund-transfer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internet-banking-fund-transfer-service
  template:
    metadata:
      labels:
        app: internet-banking-fund-transfer-service
    spec:
      containers:
        - name: internet-banking-fund-transfer-service
          image: {{ .Values.internetBankingFundTransferService.image }}
          ports:
            - containerPort: {{ .Values.internetBankingFundTransferService.containerPort }}
          command: ["/bin/bash", "-c"]
          args:
            - >
              ./wait-for-it.sh internet-banking-service-registry:8081 --timeout=50 -- true &&
              ./wait-for-it.sh internet-banking-config-server:8090 --timeout=50 -- true &&
              ./wait-for-it.sh mysql_core_db:3306 --timeout=50 -- true &&
              java -jar -Dspring.profiles.active=docker /app.jar
