apiVersion: v1
kind: Service
metadata:
  name: internet-banking-user-service
spec:
  selector:
    app: internet-banking-user-service
  ports:
    - protocol: TCP
      port: {{ .Values.internetBankingUserService.servicePort }}
      targetPort: {{ .Values.internetBankingUserService.containerPort }}
  type: ClusterIP
