apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.internetBankingConfig.name }}
  labels:
    app: {{ .Values.internetBankingConfig.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.internetBankingConfig.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.internetBankingConfig.name }}
    spec:
      containers:
        - name: {{ .Values.internetBankingConfig.name }}
          image: "{{ .Values.internetBankingConfig.image }}"
          ports:
            - containerPort: {{ .Values.internetBankingConfig.containerPort }}
