apiVersion: v1
kind: Service
metadata:
  name: internet-banking-config-server
spec:
  selector:
    app: internet-banking-config-server
  ports:
    - protocol: TCP
      port: {{ .Values.internetBankingConfig.servicePort }}
      targetPort: {{ .Values.internetBankingConfig.containerPort }}
  type: ClusterIP
