apiVersion: apps/v1
kind: Deployment
metadata:
  name: internet-banking-utility-payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internet-banking-utility-payment-service
  template:
    metadata:
      labels:
        app: internet-banking-utility-payment-service
    spec:
      containers:
        - name: internet-banking-utility-payment-service
          image: {{ .Values.internetBankingUtilityPaymentService.image }}
          ports:
            - containerPort: {{ .Values.internetBankingUtilityPaymentService.containerPort }}
          command: ["/bin/bash", "-c"]
          args:
            - >
              ./wait-for-it.sh internet-banking-service-registry:8081 --timeout=50 -- true &&
              ./wait-for-it.sh internet-banking-config-server:8090 --timeout=50 -- true &&
              ./wait-for-it.sh mysql:3306 --timeout=50 -- true &&
              java -jar -Dspring.profiles.active=docker /app.jar
