apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloakdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloakdb
  template:
    metadata:
      labels:
        app: keycloakdb
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.keycloakdb.image }}"
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.keycloakdb.env.POSTGRES_DB }}"
            - name: POSTGRES_USER
              value: "{{ .Values.keycloakdb.env.POSTGRES_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.keycloakdb.env.POSTGRES_PASSWORD }}"
          ports:
            - containerPort: {{ .Values.keycloakdb.containerPort }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data