replicaCount: 1

zipkin:
  image: openzipkin/zipkin:3
  servicePort: 9411
  containerPort: 9411

keycloak_web:
  image: quay.io/keycloak/keycloak:23.0.7
  servicePort: 8080
  containerPort: 8080
  env:
    KC_DB: postgres
    KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
    KC_DB_USERNAME: keycloak
    KC_DB_PASSWORD: password
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: password
  command: ["/opt/keycloak/bin/kc.sh", "start-dev"]
  args: ["start-dev"]

keycloakdb:
  image: postgres:15
  servicePort: 5432
  containerPort: 5432
  env:
    POSTGRES_DB: keycloak
    POSTGRES_USER: keycloak
    POSTGRES_PASSWORD: password
  storage: 1Gi

mysql:
  image: mysql:8.4.0
  rootPassword: woVERANKliGharym
  persistence:
    enabled: true
    size: 10Gi
  servicePort: 3306
  containerPort: 3306
  serviceType: ClusterIP



internetBankingConfig:
  image: sandeshsanthu/internet-banking-config-server
  containerPort: 8090
  servicePort: 8090
  name: internet-banking-config-server



internetBankingServiceRegistry:
  image: sandeshsanthu/internet-banking-service-registry
  containerPort: 8081
  servicePort: 8081
  name: internet-banking-service-registry

internetBankingApiGateway:
  image: sandeshsanthu/internet-banking-api-gateway
  containerPort: 8082
  servicePort: 8082
  name: internet-banking-api-gateway

internetBankingUserService:
  image: sandeshsanthu/internet-banking-user-service
  containerPort: 8083
  servicePort: 8083
  name: internet-banking-user-service

internetBankingFundTransferService:
  image: sandeshsanthu/internet-banking-fund-transfer-service
  containerPort: 8084
  servicePort: 8084
  name: internet-banking-fund-transfer-service

internetBankingUtilityPaymentService:
  image: sandeshsanthu/internet-banking-utility-payment-service
  containerPort: 8085
  servicePort: 8085
  name: internet-banking-utility-payment-service

coreBankingService:
  image: sandeshsanthu/internet-banking-utility-payment-service
  containerPort: 8092
  servicePort: 8092
  name: internet-core-banking-service










