jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: [
        'core-banking-service',
        'internet-banking-config-server',
        'internet-banking-fund-transfer-service',
        'internet-banking-user-service',
        'internet-banking-utility-payment-service',
        'internet-banking-service-registry',
        'internet-banking-api-gateway'
      ] }

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build
        run: ./gradlew build -x test
        working-directory: ${{ matrix.dir }}

      - name: Set up gcloud for GCS upload
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          export_default_credentials: true

      - name: Upload build artifact to GCS bucket
        run: |
          gsutil cp build/libs/${{ matrix.dir }}*SNAPSHOT.jar gs://artifacts-javas/${{ matrix.dir }}/
        working-directory: ${{ matrix.dir }}