name: Build and Upload Artifacts to GCS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [
          'core-banking-service',
          'internet-banking-config-server',
          'internet-banking-fund-transfer-service',
          'internet-banking-user-service',
          'internet-banking-utility-payment-service',
          'internet-banking-service-registry',
          'internet-banking-api-gateway'
        ]

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: ${{ matrix.dir }}

      - name: Build
        run: ./gradlew build -x test
        working-directory: ${{ matrix.dir }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCS_SA_KEY }}

      - name: Set current timestamp
        id: timestamp
        run: echo "ts=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Find built jar file
        id: jarfile
        run: |
            JAR=$(ls build/libs/${{ matrix.dir }}*SNAPSHOT.jar | head -n 1)
            echo "jar=$JAR" >> $GITHUB_OUTPUT
            working-directory: ${{ matrix.dir }}
          
      

      - name: Set up gcloud for GCS upload
        uses: google-github-actions/setup-gcloud@v2
        with:
          export_default_credentials: true
          project_id: sapient-reducer-477808-m0

      - name: Upload build artifact to GCS bucket (timestamped)
        run: |
          gsutil cp "${{ steps.jarfile.outputs.jar }}" "gs://artifacts-javas/${{ matrix.dir }}/${{ matrix.dir }}-${{ steps.timestamp.outputs.ts }}.jar"
        working-directory: ${{ matrix.dir }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dir }}:latest .
        working-directory: ${{ matrix.dir }}


      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dir }}:latest
        working-directory: ${{ matrix.dir }}
